<?php

declare(strict_types=1);

return [
    'read_only' => false,
    'checks' => [
        [
            'id' => 'appointments_write_unauthorized_guard',
            'method' => 'POST',
            'openapi_path' => '/appointments',
            'request_path' => 'api/v1/appointments',
            'auth' => 'none',
            'expected_status' => 401,
            'require_www_authenticate' => true,
        ],
        [
            'id' => 'customers_store_contract',
            'method' => 'POST',
            'openapi_path' => '/customers',
            'request_path' => 'api/v1/customers',
            'auth' => 'basic',
            'expected_status' => 201,
            'request_schema_ref' => '#/components/schemas/CustomerPayload',
            'request_required_fields' => ['firstName', 'lastName', 'email', 'timezone'],
            'response_schema_ref' => '#/components/schemas/CustomerRecord',
            'response_required_fields' => ['id', 'firstName', 'lastName', 'email', 'timezone'],
            'capture_id_to' => 'customer_id',
            'payload_builder' => 'customer',
        ],
        [
            'id' => 'appointments_store_contract',
            'method' => 'POST',
            'openapi_path' => '/appointments',
            'request_path' => 'api/v1/appointments',
            'auth' => 'basic',
            'expected_status' => 201,
            'request_schema_ref' => '#/components/schemas/AppointmentPayload',
            'request_required_fields' => ['start', 'end', 'customerId', 'providerId', 'serviceId'],
            'response_schema_ref' => '#/components/schemas/AppointmentRecord',
            'response_required_fields' => ['id', 'start', 'end', 'customerId', 'providerId', 'serviceId'],
            'capture_id_to' => 'appointment_id',
            'payload_builder' => 'appointment_create',
        ],
        [
            'id' => 'appointments_update_contract',
            'method' => 'PUT',
            'openapi_path' => '/appointments/{appointmentId}',
            'request_path_template' => 'api/v1/appointments/{appointmentId}',
            'path_params' => [
                'appointmentId' => '@state.appointment_id',
            ],
            'auth' => 'basic',
            'expected_status' => 200,
            'request_schema_ref' => '#/components/schemas/AppointmentPayload',
            'request_required_fields' => ['start', 'end', 'customerId', 'providerId', 'serviceId'],
            'response_schema_ref' => '#/components/schemas/AppointmentRecord',
            'response_required_fields' => ['id', 'start', 'end', 'customerId', 'providerId', 'serviceId', 'notes'],
            'payload_builder' => 'appointment_update',
            'skip_if_state_missing' => ['appointment_id', 'customer_id'],
        ],
        [
            'id' => 'appointments_destroy_contract',
            'method' => 'DELETE',
            'openapi_path' => '/appointments/{appointmentId}',
            'request_path_template' => 'api/v1/appointments/{appointmentId}',
            'path_params' => [
                'appointmentId' => '@state.appointment_id',
            ],
            'auth' => 'basic',
            'expected_status' => 204,
            'expect_no_content' => true,
            'skip_if_state_missing' => ['appointment_id'],
        ],
        [
            'id' => 'customers_destroy_contract',
            'method' => 'DELETE',
            'openapi_path' => '/customers/{customerId}',
            'request_path_template' => 'api/v1/customers/{customerId}',
            'path_params' => [
                'customerId' => '@state.customer_id',
            ],
            'auth' => 'basic',
            'expected_status' => 204,
            'expect_no_content' => true,
            'skip_if_state_missing' => ['customer_id'],
        ],
    ],
];
