<?php

declare(strict_types=1);

return [
    'cohort_size' => 7,
    'minimum_samples' => 5,
    'percentile_method' => 'nearest_rank',
    'required_success_jobs' => [
        'changes',
        'deep-check-bootstrap',
        'deep-check-seed-snapshot',
        'deep-runtime-suite',
        'coverage-shard-unit',
        'coverage-shard-integration',
        'coverage-delta',
    ],
    'tracked_jobs' => [
        'changes',
        'deep-check-bootstrap',
        'deep-check-seed-snapshot',
        'deep-runtime-suite',
        'coverage-shard-unit',
        'coverage-shard-integration',
        'coverage-delta',
    ],
    'critical_path_jobs' => [
        'changes',
        'deep-check-bootstrap',
        'deep-check-seed-snapshot',
        'coverage-shard-integration',
        'coverage-delta',
    ],
    'comparison_profile' => [
        'profile_version' => 1,
        'consumer_conclusions' => [
            'typed-request-contracts' => 'success',
            'deep-check-bootstrap' => 'success',
            'deep-check-seed-snapshot' => 'success',
            'deep-runtime-suite' => 'success',
            'coverage-shard-unit' => 'success',
            'coverage-shard-integration' => 'success',
            'coverage-delta' => 'success',
            'api-contract-openapi' => 'success',
            'write-contract-booking' => 'success',
            'write-contract-api' => 'success',
            'booking-controller-flows' => 'success',
            'integration-smoke' => 'success',
            'pdf-renderer-latency' => 'success',
            'heavy-job-duration-trends' => 'skipped',
        ],
        'requested_suites' => [
            'api-contract-openapi',
            'write-contract-booking',
            'write-contract-api',
            'booking-controller-flows',
            'integration-smoke',
        ],
        'change_flags' => [
            'request_contracts_required' => true,
            'deep_bootstrap_required' => true,
            'deep_runtime_asset_build_required' => true,
            'coverage_required' => true,
            'heavy_job_trends_required' => false,
            'api_contract' => true,
            'write_contract_booking' => true,
            'write_contract_api' => true,
            'booking_flows' => true,
            'integration_smoke' => true,
            'ldap_guardrail_required' => true,
            'pdf_renderer_latency_required' => true,
        ],
        'mode_flags' => [
            'event' => 'pull_request',
            'run_attempt' => 1,
            'booking_search_days' => 14,
            'retry_count' => 1,
            'start_date' => '2026-01-01',
            'end_date' => '2026-01-31',
            'integration_smoke_include_ldap' => true,
            'integration_smoke_browser_bootstrap_timeout' => 900,
            'integration_smoke_browser_evidence' => 'on-failure',
            'playwright_runtime_package' => 'playwright@1.59.0-alpha-1771104257000',
        ],
    ],
];
