services:
    uptime-kuma:
        image: 'louislam/uptime-kuma:2.5.6-slim@sha256:5db97dbbef610276e1699f3ece586c3509c8fd35de75d45ff5109761a1b377dc'
        restart: unless-stopped
        ports:
            - '${KUMA_BIND_ADDR:-127.0.0.1}:${KUMA_PORT:-3001}:3001'
        volumes:
            - '${KUMA_DATA_PATH:-uptime-kuma-data}:/app/data'

volumes:
    uptime-kuma-data:
