services:
    uptime-kuma:
        image: 'louislam/uptime-kuma:2.5.5-slim@sha256:9c56a772a7df53f444a404c579e87a27bd0c201375d00d6745a75bf8138f4342'
        restart: unless-stopped
        ports:
            - '${KUMA_BIND_ADDR:-127.0.0.1}:${KUMA_PORT:-3001}:3001'
        volumes:
            - '${KUMA_DATA_PATH:-uptime-kuma-data}:/app/data'

volumes:
    uptime-kuma-data:
