<?php

declare(strict_types=1);

/**
 * Generate the committed reviewer policy snapshot from the single JSON authority.
 * This tool intentionally emits no policy values of its own.
 */
$repoRoot = dirname(__DIR__, 2);
$contractPath = $repoRoot . '/.codex/contracts/agent-workflow.json';
$snapshotPath = $repoRoot . '/scripts/agent/lib/GeneratedReviewerPolicy.php';

$arguments = array_slice($argv, 1);
if ($arguments !== [] && $arguments !== ['--check'] && $arguments !== ['--stdout']) {
    fwrite(STDERR, "Usage: generate_reviewer_policy_snapshot.php [--check|--stdout]\n");
    exit(2);
}
if (!is_file($contractPath) || is_link($contractPath) || realpath($contractPath) !== $contractPath) {
    fwrite(STDERR, "Reviewer policy authority is not a canonical regular file.\n");
    exit(1);
}
if (is_link($snapshotPath)) {
    fwrite(STDERR, "Generated reviewer policy snapshot must not be a symbolic link.\n");
    exit(1);
}

$contract = json_decode((string) file_get_contents($contractPath), true, 512, JSON_THROW_ON_ERROR);
$policy = $contract['authority']['reviewer'] ?? null;
if (!is_array($policy)) {
    fwrite(STDERR, "Reviewer authority is missing.\n");
    exit(1);
}
$policyJson = json_encode($policy, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
if (str_contains($policyJson, "\nREVIEWER_POLICY_JSON\n")) {
    fwrite(STDERR, "Reviewer policy cannot be represented safely.\n");
    exit(1);
}
$indentedPolicyJson = preg_replace('/^/m', '    ', $policyJson);
if (!is_string($indentedPolicyJson)) {
    fwrite(STDERR, "Reviewer policy cannot be represented safely.\n");
    exit(1);
}
$content = <<<PHP
<?php

declare(strict_types=1);

// Generated by scripts/agent/generate_reviewer_policy_snapshot.php; do not edit.
return json_decode(
    <<<'REVIEWER_POLICY_JSON'
{$indentedPolicyJson}
    REVIEWER_POLICY_JSON
    ,
    true,
    512,
    JSON_THROW_ON_ERROR,
);
PHP;
$content .= "\n";

if ($arguments === ['--stdout']) {
    fwrite(STDOUT, $content);
    exit(0);
}
if ($arguments === ['--check']) {
    $actual = is_file($snapshotPath) ? (string) file_get_contents($snapshotPath) : '';
    if (!hash_equals($content, $actual)) {
        fwrite(STDERR, "Generated reviewer policy snapshot is stale.\n");
        exit(1);
    }
    exit(0);
}

if (file_put_contents($snapshotPath, $content, LOCK_EX) === false) {
    fwrite(STDERR, "Unable to write reviewer policy snapshot.\n");
    exit(1);
}
