<?php

declare(strict_types=1);

/**
 * Generate the committed code-side reviewer boundary attestation artifact.
 * This tool intentionally emits no policy values of its own.
 */
$repoRoot = dirname(__DIR__, 2);
$contractPath = $repoRoot . '/.codex/contracts/agent-workflow.json';
$runtimeAttestationPath = $repoRoot . '/scripts/agent/lib/GeneratedReviewerRuntimeAttestation.php';

$arguments = array_slice($argv, 1);
if ($arguments !== [] && $arguments !== ['--check'] && $arguments !== ['--stdout']) {
    fwrite(STDERR, "Usage: generate_reviewer_runtime_attestation.php [--check|--stdout]\n");
    exit(2);
}
if (!is_file($contractPath) || is_link($contractPath) || realpath($contractPath) !== $contractPath) {
    fwrite(STDERR, "Reviewer policy authority is not a canonical regular file.\n");
    exit(1);
}
if (is_link($runtimeAttestationPath)) {
    fwrite(STDERR, "Generated reviewer runtime boundary attestation must not be a symbolic link.\n");
    exit(1);
}

$contract = json_decode((string) file_get_contents($contractPath), true, 512, JSON_THROW_ON_ERROR);
$policy = $contract['authority']['reviewer'] ?? null;
if (!is_array($policy)) {
    fwrite(STDERR, "Reviewer authority is missing.\n");
    exit(1);
}

$attestedBoundary = $policy;
ksort($attestedBoundary, SORT_STRING);
$attestationKeys = array_keys($attestedBoundary);
$attestationDigest = hash('sha256', json_encode($attestedBoundary, JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR));
$renderedAttestationKeys = implode(
    "\n",
    array_map(static fn(string $key): string => '        ' . var_export($key, true) . ',', $attestationKeys),
);
$runtimeAttestation = <<<PHP
<?php

declare(strict_types=1);

namespace Forscherhaus\AgentHarness;

// Generated by scripts/agent/generate_reviewer_runtime_attestation.php; do not edit.
final class GeneratedReviewerRuntimeAttestation
{
    /** @var list<string> */
    public const KEYS = [
{$renderedAttestationKeys}
    ];

    public const SHA256 = '{$attestationDigest}';

    private function __construct() {}
}
PHP;
$runtimeAttestation .= "\n";

if ($arguments === ['--stdout']) {
    fwrite(STDOUT, $runtimeAttestation);
    exit(0);
}

if ($arguments === ['--check']) {
    $actualRuntimeAttestation = is_file($runtimeAttestationPath)
        ? (string) file_get_contents($runtimeAttestationPath)
        : '';
    if (!hash_equals($runtimeAttestation, $actualRuntimeAttestation)) {
        fwrite(STDERR, "Generated reviewer runtime boundary attestation is stale.\n");
        exit(1);
    }
    exit(0);
}

if (file_put_contents($runtimeAttestationPath, $runtimeAttestation, LOCK_EX) === false) {
    fwrite(STDERR, "Unable to update reviewer runtime boundary attestation.\n");
    exit(1);
}
