<?php

declare(strict_types=1);

/**
 * Generate the committed reviewer policy snapshot from the single JSON authority.
 * This tool intentionally emits no policy values of its own.
 */
$repoRoot = dirname(__DIR__, 2);
$contractPath = $repoRoot . '/.codex/contracts/agent-workflow.json';
$snapshotPath = $repoRoot . '/scripts/agent/lib/GeneratedReviewerPolicy.php';
$runtimeContractPath = $repoRoot . '/scripts/agent/lib/ReadonlyReviewerContract.php';
$runtimeAttestationStart = '    // BEGIN GENERATED REVIEWER RUNTIME BOUNDARY ATTESTATION';
$runtimeAttestationEnd = '    // END GENERATED REVIEWER RUNTIME BOUNDARY ATTESTATION';

$arguments = array_slice($argv, 1);
if (
    $arguments !== [] &&
    $arguments !== ['--check'] &&
    $arguments !== ['--stdout'] &&
    $arguments !== ['--stdout-runtime-attestation']
) {
    fwrite(STDERR, "Usage: generate_reviewer_policy_snapshot.php [--check|--stdout|--stdout-runtime-attestation]\n");
    exit(2);
}
if (!is_file($contractPath) || is_link($contractPath) || realpath($contractPath) !== $contractPath) {
    fwrite(STDERR, "Reviewer policy authority is not a canonical regular file.\n");
    exit(1);
}
if (is_link($snapshotPath) || is_link($runtimeContractPath)) {
    fwrite(STDERR, "Generated reviewer policy targets must not be symbolic links.\n");
    exit(1);
}

$contract = json_decode((string) file_get_contents($contractPath), true, 512, JSON_THROW_ON_ERROR);
$policy = $contract['authority']['reviewer'] ?? null;
if (!is_array($policy)) {
    fwrite(STDERR, "Reviewer authority is missing.\n");
    exit(1);
}
$attestedBoundary = $policy;
ksort($attestedBoundary, SORT_STRING);
$attestationKeys = array_keys($attestedBoundary);
$attestationDigest = hash('sha256', json_encode($attestedBoundary, JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR));
$renderedAttestationKeys = implode(
    "\n",
    array_map(static fn(string $key): string => '        ' . var_export($key, true) . ',', $attestationKeys),
);
$runtimeAttestation = <<<PHP
{$runtimeAttestationStart}
    private const RUNTIME_BOUNDARY_ATTESTATION_KEYS = [
{$renderedAttestationKeys}
    ];

    private const RUNTIME_BOUNDARY_ATTESTATION_SHA256 = '{$attestationDigest}';
{$runtimeAttestationEnd}
PHP;

$policyJson = json_encode($policy, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
if (str_contains($policyJson, "\nREVIEWER_POLICY_JSON\n")) {
    fwrite(STDERR, "Reviewer policy cannot be represented safely.\n");
    exit(1);
}
$indentedPolicyJson = preg_replace('/^/m', '    ', $policyJson);
if (!is_string($indentedPolicyJson)) {
    fwrite(STDERR, "Reviewer policy cannot be represented safely.\n");
    exit(1);
}
$content = <<<PHP
<?php

declare(strict_types=1);

// Generated by scripts/agent/generate_reviewer_policy_snapshot.php; do not edit.
return json_decode(
    <<<'REVIEWER_POLICY_JSON'
{$indentedPolicyJson}
    REVIEWER_POLICY_JSON
    ,
    true,
    512,
    JSON_THROW_ON_ERROR,
);
PHP;
$content .= "\n";

if ($arguments === ['--stdout']) {
    fwrite(STDOUT, $content);
    exit(0);
}
if ($arguments === ['--stdout-runtime-attestation']) {
    fwrite(STDOUT, $runtimeAttestation . "\n");
    exit(0);
}
if ($arguments === ['--check']) {
    $actual = is_file($snapshotPath) ? (string) file_get_contents($snapshotPath) : '';
    if (!hash_equals($content, $actual)) {
        fwrite(STDERR, "Generated reviewer policy snapshot is stale.\n");
        exit(1);
    }
}

$runtimeSource = is_file($runtimeContractPath) ? (string) file_get_contents($runtimeContractPath) : '';
$startOffset = strpos($runtimeSource, $runtimeAttestationStart);
$endOffset = strpos($runtimeSource, $runtimeAttestationEnd);
if (
    $startOffset === false ||
    $endOffset === false ||
    $endOffset < $startOffset ||
    strpos($runtimeSource, $runtimeAttestationStart, $startOffset + 1) !== false ||
    strpos($runtimeSource, $runtimeAttestationEnd, $endOffset + 1) !== false
) {
    fwrite(STDERR, "Reviewer runtime boundary attestation markers are invalid.\n");
    exit(1);
}
$runtimeAttestationLength = $endOffset + strlen($runtimeAttestationEnd) - $startOffset;
$actualRuntimeAttestation = substr($runtimeSource, $startOffset, $runtimeAttestationLength);

if ($arguments === ['--check']) {
    if (!hash_equals($runtimeAttestation, $actualRuntimeAttestation)) {
        fwrite(STDERR, "Generated reviewer runtime boundary attestation is stale.\n");
        exit(1);
    }
    exit(0);
}

$updatedRuntimeSource =
    substr($runtimeSource, 0, $startOffset) .
    $runtimeAttestation .
    substr($runtimeSource, $startOffset + $runtimeAttestationLength);
if (!hash_equals($runtimeSource, $updatedRuntimeSource)) {
    if (file_put_contents($runtimeContractPath, $updatedRuntimeSource, LOCK_EX) === false) {
        fwrite(STDERR, "Unable to update reviewer runtime boundary attestation.\n");
        exit(1);
    }
}

if (file_put_contents($snapshotPath, $content, LOCK_EX) === false) {
    fwrite(STDERR, "Unable to write reviewer policy snapshot.\n");
    exit(1);
}
