<?php

declare(strict_types=1);

// Generated by scripts/agent/generate_reviewer_policy_snapshot.php; do not edit.
return json_decode(
    <<<'REVIEWER_POLICY_JSON'
    {
        "invocation": "scripts/agent/trusted_base_launcher.sh",
        "payload_path": "scripts/agent/run_readonly_reviewer.sh",
        "invocation_source": "external_system_git_materialized_exact_base_launcher_then_private_exact_base_payload",
        "bootstrap_materialization_policy": "absolute_system_git_clean_environment_private_blob_verification_before_any_repository_code_execution",
        "launcher_materialization_guard": "required_external_exact_blob_path_and_marker",
        "trust_anchor": "review_base_commit",
        "review_base_ref": "refs/remotes/origin/main",
        "review_base_remote_url": "https://github.com/robinbeier/forscherhaus-appointments.git",
        "review_base_policy": "exact_merge_base_with_live_pinned_public_remote_main_and_matching_tracking_ref",
        "review_base_remote_transport": "unauthenticated_read_only_ls_remote_clean_environment",
        "requires_base_runner": true,
        "direct_checkout_execution": "forbidden_fail_closed",
        "runtime_configuration_change_policy": "external_bootstrap_review",
        "shell_runtime_configuration": "root_owned_system_git_then_clean_bash_environment",
        "transport_environment_policy": "fixed_direct_no_ambient_proxy_or_endpoint_override",
        "temporary_directory_policy": "private_system_temp_bundle_and_internal_runtime_only",
        "php_runtime_configuration": "exact_base_attested_binary_and_dynamic_closure_ignore_ambient_ini",
        "git_runtime_configuration": "ignore_ambient_and_disable_helpers",
        "git_lazy_fetch": "disabled",
        "tool_path_policy": "explicit_primary_codex_with_verified_private_copy",
        "repository_root_policy": "canonical_physical_root",
        "codex_identity_check": "official_release_binary_sha256_platform_version_and_dynamic_closure",
        "codex_version": "0.145.0",
        "codex_version_policy": "exact_machine_pinned_version_with_bounded_build_metadata",
        "codex_binary_materialization_policy": "private_copy_rehashed_and_closure_attested_before_first_execution",
        "codex_dynamic_dependency_policy": "system_sealed_only_non_system_dependency_rejected",
        "codex_binary_sha256_by_platform": {
            "Darwin-arm64": "1da3f4e0e96028b8a771814293c3033dafd1971f943f6c7e79b0897fe705f590",
            "Darwin-x86_64": "6db9193ce2c9a8cef2b5482612cde24202a4329dfc34f4687a036d5d7da619af"
        },
        "codex_release_archive_sha256_by_platform": {
            "Darwin-arm64": "072a30a65f05666735889ef0f60b56db186adbdde9d5c5cc1a64be0b598530fe",
            "Darwin-x86_64": "4216d7a40aa49d74b65fab93d2a86d2e25a902482b827dbdb3f357777b09fadf"
        },
        "codex_closure_sha256_by_platform": {
            "Darwin-arm64": "cb24bcb9e973a8258c763e4b2777a398799c653996b395b3e2ab4cf1aa806a0a",
            "Darwin-x86_64": "a74149a742b113e72e0d59ab1f86786dd52bb2538cdbc42794b718155f06d90b"
        },
        "codex_authentication_source": "host_codex_login_without_connector_authority",
        "codex_authentication_home_policy": "isolated_runtime_home_read_only_link_to_canonical_auth_file",
        "codex_api_key_override_policy": "reject_ambient_api_keys",
        "finding_path_policy": "normalized_exact_diff_paths",
        "finding_text_policy": "bounded_privacy_safe_prose",
        "web_search": "disabled",
        "review_checkout": "deterministic_exact_commit_bundle",
        "review_checkout_symlink_policy": "reject_all_tracked_symlinks",
        "review_bundle_parent_policy": "private_system_temp_random_directory",
        "review_bundle_contents": "zero_context_text_patch_manifest_changed_paths_and_trusted_policy",
        "review_bundle_manifest_policy": "deterministic_sha256_base_head_binding",
        "review_bundle_context_policy": "zero_context_changed_lines_only_no_full_base_or_head_blobs",
        "review_bundle_hunk_header_policy": "strip_unchanged_section_text_before_model_input",
        "review_bundle_binary_policy": "reject_before_model_input",
        "review_bundle_file_allowlist": "manifest_patch_changed_paths_and_trusted_policy_only",
        "review_instruction_policy": "trusted_base_policy_as_developer_instructions_untrusted_bundle_as_user_input",
        "prompt_role_preflight": "pinned_cli_requires_developer_policy_and_user_bundle_channels",
        "review_input_policy": "bounded_deterministic_json_serialization_as_untrusted_user_stdin",
        "review_original_worktree_access": "not_model_visible",
        "isolation_platform": "darwin_seatbelt_fail_closed_elsewhere",
        "isolation_profile": "default_deny_runtime_allowlist_exact_bundle_and_auth_read_only",
        "isolation_preflight": "bundle_readable_foreign_temp_and_original_worktree_denied_exact_auth_file_only_no_home_write",
        "model_tool_surface": "derived_exact_release_catalog_without_shell_patch_image_search_or_external_tools",
        "codex_sandbox_mode": "read-only",
        "codex_approval_policy": "never",
        "output_schema_path": "scripts/agent/readonly-review-output.schema.json",
        "bootstrap_paths": [
            ".codex/contracts/agent-workflow.json",
            "scripts/agent/trusted_base_launcher.sh",
            "scripts/agent/run_readonly_reviewer.sh",
            "scripts/agent/lib/trusted_base_payload_runtime.sh",
            "scripts/agent/readonly-review-output.schema.json",
            "scripts/agent/readonly-reviewer.sb",
            "scripts/agent/verify_trusted_php_runtime.py",
            "scripts/agent/lib/trusted_runtime_primitives.py",
            "scripts/agent/readonly_review_bundle.php",
            "scripts/agent/readonly_reviewer_contract.php",
            "scripts/agent/lib/RepoPath.php",
            "scripts/agent/lib/ReadonlyReviewBundle.php",
            "scripts/agent/lib/ReadonlyReviewerContract.php",
            "scripts/agent/lib/GeneratedReviewerPolicy.php",
            "scripts/agent/lib/ReadonlyReviewerModelPolicy.php",
            "scripts/agent/lib/ReadonlyReviewOutput.php",
            "scripts/agent/lib/readonly_reviewer_bundle_runtime.sh",
            "scripts/agent/lib/readonly_reviewer_isolated_runtime.sh"
        ],
        "policy_context_paths": [
            "AGENTS.md",
            "code_review.md"
        ],
        "profiles": {
            "correctness_security": {
                "instructions": ".codex/agents/reviewer-correctness.toml",
                "model": "gpt-5.4",
                "reasoning": "high"
            },
            "design_maintainability": {
                "instructions": ".codex/agents/reviewer-design.toml",
                "model": "gpt-5.4-mini",
                "reasoning": "medium"
            },
            "tests_regression_flake": {
                "instructions": ".codex/agents/reviewer-tests.toml",
                "model": "gpt-5.4-mini",
                "reasoning": "medium"
            }
        },
        "disabled_features": [
            "apps",
            "plugins",
            "browser_use",
            "browser_use_external",
            "browser_use_full_cdp_access",
            "computer_use",
            "image_generation",
            "in_app_browser",
            "memories",
            "skill_search",
            "skill_mcp_dependency_install",
            "auth_elicitation",
            "tool_call_mcp_elicitation",
            "multi_agent",
            "multi_agent_v2",
            "hooks",
            "shell_tool",
            "unified_exec",
            "code_mode",
            "code_mode_only",
            "code_mode_host",
            "shell_snapshot",
            "workspace_dependencies",
            "goals",
            "chronicle",
            "tool_suggest",
            "remote_plugin",
            "plugin_sharing",
            "deferred_executor",
            "executor_capability_discovery",
            "request_permissions_tool",
            "default_mode_request_user_input"
        ],
        "filesystem": "outer_seatbelt_default_deny_exact_bundle_read_only_runtime_scratch_only",
        "network": "outer_codex_transport_no_model_network_tool_or_external_credentials",
        "approval_policy": "outer_seatbelt_plus_codex_read_only_no_model_tools",
        "inherits_user_config": false,
        "inherits_execpolicy_rules": false,
        "output_binds_base_sha": true,
        "allows_external_connectors": false,
        "allows_delegation": false,
        "denied_mutations": [
            "file_write",
            "commit",
            "push",
            "pr_mutation",
            "pr_comment",
            "pr_review",
            "check_rerun",
            "merge",
            "linear_mutation",
            "workpad_update"
        ]
    }
    REVIEWER_POLICY_JSON
    ,
    true,
    512,
    JSON_THROW_ON_ERROR,
);
