<?php

declare(strict_types=1);

namespace Forscherhaus\AgentHarness;

// Generated by scripts/agent/generate_reviewer_runtime_attestation.php; do not edit.
final class GeneratedReviewerRuntimeAttestation
{
    /** @var list<string> */
    public const KEYS = [
        'allows_delegation',
        'allows_external_connectors',
        'approval_policy',
        'bootstrap_guard_pathspecs',
        'bootstrap_materialization_policy',
        'bootstrap_paths',
        'codex_api_key_override_policy',
        'codex_approval_policy',
        'codex_authentication_home_policy',
        'codex_authentication_source',
        'codex_binary_materialization_policy',
        'codex_binary_sha256_by_platform',
        'codex_closure_sha256_by_platform',
        'codex_dynamic_dependency_policy',
        'codex_identity_check',
        'codex_release_archive_sha256_by_platform',
        'codex_sandbox_mode',
        'codex_version',
        'codex_version_policy',
        'denied_mutations',
        'direct_checkout_execution',
        'disabled_features',
        'filesystem',
        'finding_path_policy',
        'finding_text_policy',
        'git_lazy_fetch',
        'git_runtime_configuration',
        'inherits_execpolicy_rules',
        'inherits_user_config',
        'invocation',
        'invocation_source',
        'isolation_platform',
        'isolation_preflight',
        'isolation_profile',
        'launcher_materialization_guard',
        'model_tool_surface',
        'network',
        'output_binds_base_sha',
        'output_schema_path',
        'payload_path',
        'php_runtime_configuration',
        'policy_context_paths',
        'profiles',
        'prompt_role_preflight',
        'repository_root_policy',
        'requires_base_runner',
        'review_base_policy',
        'review_base_ref',
        'review_base_remote_transport',
        'review_base_remote_url',
        'review_bundle_binary_policy',
        'review_bundle_contents',
        'review_bundle_context_policy',
        'review_bundle_file_allowlist',
        'review_bundle_hunk_header_policy',
        'review_bundle_manifest_policy',
        'review_bundle_parent_policy',
        'review_checkout',
        'review_checkout_tree_entry_policy',
        'review_input_policy',
        'review_instruction_policy',
        'review_original_worktree_access',
        'runtime_configuration_change_policy',
        'shell_runtime_configuration',
        'temporary_directory_policy',
        'tool_path_policy',
        'transport_environment_policy',
        'trust_anchor',
        'web_search',
    ];

    public const SHA256 = '27c265bfc8f5121aaeade6bca6ad5a2a440f24834f878d4795ff318255393782';

    private function __construct() {}
}
